### ISSUE TITLE
Cannot create or edit tournaments - 422 error

### ISSUE THREAD

**Issue by JarekWarsaw** [Project-NISEI/cobra#22]
Hi!
I tried to edit my [private tournament created a week ago](https://cobr.ai/tournaments/2238/edit) (change title or privacy). In both cases got rejected with `The change you wanted was rejected (422)`.
I'm also unable to create a new tournament - same result `Status Code: 422`.
Not sure how to proceed.
All requests were done in the past 15 minutes. So in logs look around `2021-12-02 08:50 GMT`

**Comment by JarekWarsaw** [comment]
For the record the problem is no longer occurring, so feel free to close this ticket. If anyone helped here - thanks!
But it's interesting why it happened in the first place.

**Comment by plural** [comment]
we were missing some settings in our nginx config and tidied that up this morning.  Thanks for the report and sorry for the interruption!
