### ISSUE TITLE
Retrieve Decklists via NRDB Auth for Open List Cuts

### ISSUE THREAD

**Issue by Orbital-Tangent** [Project-NISEI/cobra#35]
This may require that profiles for players be implemented in some fashion, via NRDB Auth like ABR. Perhaps this could even be linked to a person's ABR profile somehow.

Two things would need to be implemented in the tournament setup: 1) a setting for "Decklists Required? Y/N" and 2) a setting for "Open Lists in Cut? Y/N"

With both active, during registration someone could link their list from their NRDB profile. This list, or a link to it, would be stored and accessible by a NRDB authed opponent when the two are paired during the Cut.

TOs would need admin access to lists at all times for deck checks, and having tools to dynamically open up or close list sharing during Cut rounds would also be desirable.

**Comment by Orbital-Tangent** [comment]
In addition to submitting decklists, having them properly formatted for printout would be aces. We'd need the person's name, handle, Corp ID/Deck, and Runner ID/Deck. Basically, we should tailor e-submit of a list to have all the same questions answered as a paper copy (Name/Pronouns/Event/Handle/Decks/Stream Consent/Etc).

**Comment by haradan** [comment]
This is really a lot of different features, with integrations between several systems. This might be worth splitting up.

1. NRDB-based deck registration, with the player choosing from their private decks at registration (flag on tournament to replace the current ID fields?)
2. Retrieve the chosen deck from NRDB and store in Cobra's database
3. Possibly some alternative for deck registration by the TO
4. Display registered decks to the TO
5. Include links to NRDB in export to ABR
6. Open list cuts where registered decks are displayed to the players playing each other (or everyone?)

**Comment by haradan** [comment]
This should be finished now, though I've raised a few more issues for potential improvements. I'm closing this and we can pick up on separate issues if necessary.
