### ISSUE TITLE
Player Profiles via NRDB Auth and/or ABR Linking

### ISSUE THREAD

**Issue by Orbital-Tangent** [Project-NISEI/cobra#36]
It would be nice to have player profiles implemented on the site as objects to help with automating data entry. These could be used for both player and TO focused features, like registration, reporting, stats tracking, decklist linking, and many other data sharing ideas.

Ideally these would use existing NRDB Auth and possibly link back to ABR profiles, though Cobra would probably need to store data entry fields unique to the site like Name/Discord Handle/Jinteki Handle/etc.

**Comment by plural** [comment]
Orbs, does the player self-registration we added take care of what you needed or is there still more you want to see here?

**Comment by haradan** [comment]
Closing. If we want more features, eg. player stats tracking, we can raise that separately.
