### ISSUE TITLE
Allow intentional draw results to be entered

### ISSUE THREAD

**Issue by plural** [Project-NISEI/cobra#7]
Originally https://github.com/muyjohno/cobra/issues/138

TO should be able to enter a 3-3 that does not contribute points to either side (for statistical accuracy)

**Comment by haradan** [comment]
Is there anything left to do on this?

**Comment by haradan** [comment]
It looks like this was implemented by https://github.com/Project-NISEI/cobra/pull/79. Closing, we can raise any improvements separately.
