### ISSUE TITLE
full screen timer option

### ISSUE THREAD

**Issue by plural** [Project-NISEI/cobra#99]
for big tournaments it would be great to have a full screen view of the timer that could be projected or shown on a big screen/tablet/whatevs.

**Comment by Orbital-Tangent** [comment]
For full screen mode it's not a true full screen, just something that covers the area of a full browser tab. We'd like to be able to snap multiple open tabs to different areas of the screen for things like Worlds when multiple events are going on all at once.

It would be nice to be able to do a color coded background, and a name to display above the timer. The timer itself should probably blink once the time is up and/or the background could too. A very slow blink.

**Comment by haradan** [comment]
I think this was done in PR https://github.com/Project-NISEI/cobra/pull/121. I'll close it and we can make a new issue if we want more changes.
